apiVersion: v1
kind: Pod
metadata:
  name:   alpine-cluster-2
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "blue-net",
          "interface":"net1",
          "cni-args": {
            "mac":"aa:bb:cc:dd:02:01",
            "dataplane":"linux",
            "ipConfig":{
              "ipv4":{
                "address":"1.2.2.2/30",
                "gateway":"1.2.2.1",
                "routes":[
                  "1.2.0.0/16","1.1.0.0/16"
                ]
              },
              "ipv6":{
                "address":"abcd::1.2.2.2/126",
                "gateway":"abcd::1.2.2.1",
                "routes":[
                  "abcd::1.2.0.0/112"
                ]
              }
            }
          }
        }
      ]
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
                - master
  containers:
    - name: alpine-cluster-2
      image: alpine:latest
      command: ["/usr/bin/tail"]
      args: ["-f", "/dev/null"]
      securityContext:
        privileged: false
      env:
        - name: KUBERNETES_POD_UID
          valueFrom:
            fieldRef:
               fieldPath: metadata.uid
      volumeMounts:
        - name: dpdk
          mountPath: /dpdk
          subPathExpr: $(KUBERNETES_POD_UID)
  volumes:
    - name: dpdk
      hostPath:
        path: /var/run/platter/containers
