apiVersion: v1
kind: Secret
metadata:
  name: platter-secrets
  namespace: kube-system
data:
  root-password: bXktcm9vdC1wYXNzd29yZA==
  crpd-license: |
    MTkgMjQzIE5pIExPTkcgTk9STUFMIFNUQU5EQUxPTkUgQUdHUiAxX0tFWVMgSU5GSU5JVEVfS0VZ
    UyAxOCBNQVkgMjAyMSAwIDAgMTggTUFZIDIwMjIgMCAwIE5pTCBTTE1fQ09ERSBERU1PIE5pTCBO
    aUwgTmkgTmlMIE5pTCAxNV9NSU5TIE5pTCAwIG1OdTd4SWxITkdsYVV2Y2dReGo3UWFOamw3cE5W
    b1hhRDdEZ0JpUzExNWhTR2U3ckxqd1cxQW5PZ3czUmZGWVByeUJMY1kydnliUi9kbEYxSkR0WjBI
    OWIrb1AvdFQ2L21vczFBZWw5V1YvdGlUZVhkbytqcnJadVJlcHVRZ3FSYUN1N3ZPMkkwR0xnQ0tX
    cWtkUDZDbi9uaTArNERoT08zYkpyUUo1TzRGK0J2WnJOSUwrdWRjL1hGaDRsb1VvR3JxRnJaOXRq
    L1pIdlhYNGtnb3NPeElHa2pFMHVYb2RhTDVwaFdSK1RqdHpJdkdmZ0dha0VudXhmRlNlRmlla3dT
    TlhIZkkvYU9wai9RRjJqN3l1VFVFZjhoOUI5QXRObjJYd0FyMGUwT29GbVVhRWFhKzJSZVJEWnd1
    WkgyYXQ1b0YyM1R0N096QWtQU2JTUnMxNVRFSUZTMG8rYy9lRnFQOXpFZi84U2tjYzZXanc2c0Ft
    Vmw0S2xpU3ZQV0E2T2tEYjNnMlIwbkhHZ1RINnF2K3VLREtwUnl0NEJHNjE4d0hDT1JJNTNaNTM5
    dmtTWjRLY0NrUWV2aXErTHVSK0wyeE9BQnlTVEpzNEx3czZ5RHUvMzcyZ3JUdUVrSVVIakpTTkJP
    ZEdMU1ZIbjJFZEQzdTdrc2IxdVhONldKckxVcmVvYzdkR0pZRWVqWGd1aVV0RWYramRuUzN4VnZC
    QmVzQ1FGNHhHc05ibG0yWmovVDVQSlN6UWZ1ZmlQOGdHSWN4dWRCUzBOdTBzRmlxOWhFMFNIcVFV
    RVVrTkNNZ3VEQ1FVRVVrTkNNZ1lCQVFjQkFRUWxPR0l4WWpabU1XUXRNemMyT1MwMFpqUmxMV0l6
    T0RjdE16UmxNekpsWlRrMk0ySmtBQWdCQVFsQXBjblNLVkdZdXAvSTh5Q3pxMVQyb09mVnpRd0lz
    NldISk92SUhPTGkzMFNFOHhwblVFeW4ydlZOU3ZBUm84MzIxOUV1TUFnMlladUpZZWVYbjZTMTFR
    cUNEakNDQVFvQ2dnRUJBTmpqSUJFa0lkWDgrQzQxMmRFcGc3S3p4aWRuQWVjMU9BajdFSmtJOUJZ
    NTQxR0h4ZU5ad3hqdWp1SnFTSjh1Vms4eFNXRXFldGU5ZmFHY2d4RmJDV0djSjZpdHpjOHJNRFFW
    WTl3cWtoOGR4NlNncnRaNmdEZGJBdS9ZVzhXdHk3Rzd4bXR1ZHRvN1RNNGEzZXhkekhjbkJuc0d0
    anRPdEs2d2MvV2E2TVlxNmgrbWNlSTVzeFVTVzRHVisxRkRpYk1GdDIrWEV5cFRzbC8yR0pkYTBD
    S0dtZm45V0xSR2lFUjBQSS9ZL0Y1L3h1QUU5VjQwQlRoL1dINk4vVHp4RVJxOWJBaGppSlNxV0Zt
    U1lUK2k5eDZpREJkdHJiQUZpUzFaRGlEd3JpUHoyYVpPVlRKbUdhQmR5akhhT1pFbndFNEtMVnVy
    bjRha2pVbTRVZXA3dTRzQ0F3RUFBUVFsT0dJeFlqWm1NV1F0TXpjMk9TMDBaalJsTFdJek9EY3RN
    elJsTXpKbFpUazJNMkprQUFjQkFReUNBSS85QmwwVWh1RVdZSE00cW5aamJoZ0t4U2JNMXdOTmI4
    YmhrMUV0WFZJM1g5RHlnYmRLNmYvZGk5RXFEajNFMC8zcmxYV2hTU0FubktpWWVZcWpBUUJMU3dN
    Tm53bmxSMWtrRGtIY285M1hMWVNvUVZQWks0Y20zZlRFUHVtYkl0VTFFWGppcWk0azdycHU2ZWlB
    OGxSNmlDRWdIeElhQk80OWdPT09wdFNYeVRqZFBDN294SzV1M05uL1R4V0NOQlRHNDZIQVU3cUxS
    OW9LbW5wa1R4bmFtckdCRDltajZ6blkvMjBIaGhLOFBtTmxsQzY1RDJNVUxJaXc4RTgzSnhITXc1
    cGtSNnRJUTd3blFnTE5teWZLdEFoWHN6VjFpVVVod2FuZUdVVnIzNFBFd2dzaWhheFVpcWk1Ui9r
    Z0lNNmx2ZzlEWTMrNUtyL080WWxjLzBNQUFBSy8jS2V5VHlwZT1EZW1vTGFiI0FJRD0wYWNiMjkw
    Yi1hODY4LTRmMmEtYjE5MS1mNDZlMmYxMzUzM2YgU0lHTj0wNzI4QjdBMkMyOEY3NDI4QzcyNUIx
    MUE5M0ZCMzk2RDdCQ0I5MjJGQjlDM0IyODU2MzgxOThCOUNDMTM0NEM4MENFQkIxMTcxOUUyQThC
    ODFEQkU=

