apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: small-us-west-2
  region: us-west-2

vpc:
  cidr: 10.20.0.0/16
  autoAllocateIPv6: false
  clusterEndpoints:
    publicAccess: true
    privateAccess: true


nodeGroups:
  - name: ng-west-2
    instanceType: t4g.small
    desiredCapacity: 3
    ssh: # import default public key (~/.ssh/id_rsa.pub)
      allow: true       # allow ssh from Internet
